// World-viewer contracts shared by main and renderer (type-only). A "world" is a Minecraft save
// folder (level.dat + region/*.mca) opened view-only and flown through in 3D — parallel to the
// single-structure `StructureData` path, but streamed chunk-by-chunk with LOD.
import type { PaletteEntry, StructureEntity } from './structure';

/** A dimension's resource id — the three vanilla ones OR a mod dimension `namespace:path`
 *  (e.g. `theplacebeyond:bleak_db599711`). Resolved to a region folder in `world-paths.ts`. */
export type DimensionId = string;

/** A dimension present on disk (has region data), with a display label for the HUD. Only dimensions
 *  that actually generated (their `region/` holds `.mca`) are listed — an ungenerated nether/end
 *  never went to isn't offered. */
export interface WorldDimension {
  /** Resource id, e.g. `minecraft:overworld` or `theplacebeyond:bleak_db599711`. */
  id: DimensionId;
  /** Short display label (vanilla names localised; a mod dim shows its path). */
  label: string;
}

/** Everything the shell needs to open a world and seed navigation, read from `level.dat`. */
export interface WorldMeta {
  /** Absolute path to the world folder (the dir holding `level.dat`). */
  root: string;
  /** Display name (`LevelName`, falls back to the folder basename). */
  name: string;
  /** NBT `DataVersion` — gates the decoder (1.18+ = 2860, MC 1.21.1 = 3955). */
  dataVersion: number;
  /** Human MC version string when present (`Version.Name`, e.g. "1.21.1"). */
  versionName: string | null;
  /** Dimensions that actually have region data on disk (vanilla + mod), with display labels. */
  dimensions: WorldDimension[];
  /** World spawn (blocks). */
  spawn: [number, number, number];
  /** Last known player position (blocks), when the save records one. */
  player: [number, number, number] | null;
  /** World-generation seed as a decimal string (signed 64-bit), or null when unknown.
   *  Drives the seed-derived slime-chunk overlay. */
  seed: string | null;
  /** Dev-only: an explicit initial camera look target (BW_WORLD_LOOK) so a headless capture can aim
   *  at a specific feature (a cave, a world edge). Ignored in normal use. */
  debugLook?: [number, number, number];
}

/** A remembered world for the recents list / Welcome screen (mirrors `Workspace`'s shape). */
export interface WorldRef {
  /** Absolute path to the world folder. */
  root: string;
  /** Display name. */
  name: string;
}

/** A named camera bookmark in a world (persisted per world root in userData). */
export interface WorldWaypoint {
  name: string;
  /** Camera position (world coords) the jump restores. */
  pos: [number, number, number];
  /** The dimension it was captured in (a jump switches there first). */
  dimension: DimensionId;
}

/** A region coordinate `(rx, rz)` present on disk for a dimension (drives the load plan / minimap).
 *  A region spans 32×32 chunks; `chunkX >> 5 === rx`. */
export interface RegionRef {
  rx: number;
  rz: number;
}

/** A generated structure found in a world (village, stronghold, mod structure, …) — its id and a
 *  jump-to position. Powers the "find structures" search (minutes of flying → a click). */
export interface StructureLocation {
  /** Structure resource id, e.g. `minecraft:village_plains`. */
  id: string;
  /** Short label (the id's path). */
  label: string;
  x: number;
  y: number;
  z: number;
}

// ── World editing (v2.2) ─────────────────────────────────────────────────────────────

/** One pending block edit at an ABSOLUTE world position, as it crosses IPC to the write path.
 *  `name`/`properties` are the NBT-shaped block state (main maps them to `{Name, Properties}`).
 *  Air (`minecraft:air`) is an edit like any other. */
export interface WorldEditBlock {
  x: number;
  y: number;
  z: number;
  name: string;
  properties?: Record<string, string>;
  /** Full block-entity NBT to attach at this cell (must carry `id`; coordinates are stamped
   *  from the edit position by the write path). Omitted ⇒ any existing block entity at the
   *  cell is removed — a changed block never keeps a stale chest/spawner record. */
  blockEntity?: Record<string, unknown>;
}

/** One entity to spawn into the world (Place structure into world §2.2 fidelity). Unlike block
 *  edits, entities aren't cell-keyed — they ride the apply payload as their own list. */
export interface WorldEntityEdit {
  /** Absolute world position (doubles) the entity lands at. */
  pos: [number, number, number];
  /** The entity compound (must carry `id`). `Pos` is stamped from `pos` and `UUID` is
   *  regenerated by the write path (a pasted copy must never duplicate a UUID). */
  nbt: Record<string, unknown>;
}

/** Result of opening a world-edit session. `lockExclusive` is true only where the OS gave a REAL
 *  mutual-exclusion guarantee on `session.lock` (Windows); on macOS/Linux the hold is advisory and
 *  the UI must surface a "make sure Minecraft is closed" caution. */
export interface WorldEditOpenResult {
  lockExclusive: boolean;
}

/** A chunk the write path REFUSED (proto chunk, unknown DataVersion, unreadable) — reported, never
 *  "best-effort" written. */
export interface WorldRefusedChunk {
  cx: number;
  cz: number;
  reason: string;
}

/** One backup set under `<save>/blockwright-backups/` (mirrors main's `BackupSet`). */
export interface WorldBackupInfo {
  id: string;
  createdMs: number;
  /** Save-root-relative paths of the backed-up files. */
  files: string[];
  bytes: number;
}

/** What a Save-to-World actually did (mirrors main's `WorldEditReport`, serializable). */
export interface WorldEditApplyResult {
  changedBlocks: number;
  /** Entities actually written into `entities/` region files (refused chunks not counted). */
  placedEntities: number;
  editedChunks: { cx: number; cz: number }[];
  /** Absolute paths of the region files rewritten (block + poi + entities). */
  regions: string[];
  /** The backup taken before this save touched new files (null = all already backed up). */
  backup: WorldBackupInfo | null;
  refused: WorldRefusedChunk[];
}

/** An inclusive world-cell box to extract into a structure (v2.2 §4). */
export interface WorldExtractBox {
  min: [number, number, number];
  max: [number, number, number];
}

/** Result of extracting a world region into a structure. On success `path` is a freshly written
 *  temp `.nbt` the renderer either opens as a tab or feeds to the Export As / jigsaw-split flow;
 *  `oversized` means the region exceeds a Structure-Block axis limit (offer jigsaw on save);
 *  `refusedChunks` counts columns in the box that couldn't be read (proto/pre-1.13), skipped. */
export type WorldExtractResult =
  | {
      ok: true;
      path: string;
      name: string;
      size: [number, number, number];
      oversized: boolean;
      blocks: number;
      blockEntities: number;
      entities: number;
      refusedChunks: number;
    }
  | { ok: false; error: string };

/** One 16×16×16 section of a render payload. `uniform` sections carry no grid — every cell is the
 *  palette index `fill` (a stone/air fill costs nothing over IPC). */
export interface ChunkSectionPayload {
  sectionY: number;
  /** 4096 indices into the column palette (YZX), or null when `uniform`. */
  blocks: Uint16Array | null;
  uniform: boolean;
  /** Palette index that fills a uniform section (ignored when `blocks` is present). */
  fill: number;
  /** Biome ids present in this section (4×4×4 quart resolution); absent/null when the chunk
   *  predates paletted biomes (or for synthesized sections — the edit compositor's). Drives
   *  the world cursor readout's biome line. */
  biomePalette?: string[] | null;
  /** 64 indices into `biomePalette` (YZX quarts); absent/null when uniform (one biome). */
  biomes?: Uint8Array | null;
}

/** A chunk column resolved to renderable data, streamed to the renderer's mesh worker. The palette
 *  is unified across the column's sections (deduped by block-state string) and already carries
 *  resolved models + texture keys + fallback colours — the same shape the structure mesh path
 *  consumes, so the geometry core is shared. Typed arrays cross IPC via structured clone. */
export interface ChunkRenderPayload {
  cx: number;
  cz: number;
  palette: PaletteEntry[];
  sections: ChunkSectionPayload[];
  /** Every texture key referenced by the palette (the renderer preloads these before meshing). */
  textureKeys: string[];
  /** MOTION_BLOCKING surface (world Y per column, 256 XZ) for the mid LOD, or null. */
  heightmap: Int16Array | null;
  /** Dominant biome grass/foliage tint (sRGB 0..1) applied to `tintindex` faces, or null (default
   *  green). Per-chunk, so foliage varies by biome without a full per-block colormap. */
  grassTint: [number, number, number] | null;
  /** Entities to draw (armor stands, item frames, mobs) resolved to render shapes — their texture
   *  keys are folded into `textureKeys`. Only drawn at the near LOD. Empty when the chunk has none. */
  entities: StructureEntity[];
  /** True when the chunk exists on disk but has no renderable (non-air) sections AND no entities. */
  empty: boolean;
}
